const pl = {
  authentication: {
    account: "Konto",
    accountOfCurrentUser: "Konto bieżącego użytkownika",
    accountVerified: "Konto zweryfikowane",
    alreadyActivated: "Już aktywowane",
    alreadyLoggedIn: "Już zalogowany",
    apiKey: "Klucz API",
    authenticated: "Uwierzytelniono",
    backToLogin: "Powrót do logowania",
    beginCreateFirstUser: "Rozpocznij tworzenie pierwszego użytkownika",
    changePassword: "Zmień hasło",
    checkYourEmailForPasswordReset: "Sprawdź e-mail, aby zresetować hasło",
    confirmGeneration: "Potwierdź generowanie",
    confirmPassword: "Potwierdź hasło",
    createFirstUser: "Utwórz pierwszego użytkownika",
    emailNotValid: "Nieprawidłowy adres e-mail",
    emailOrUsername: "E-mail lub nazwa użytkownika",
    emailSent: "E-mail wysłany",
    emailVerified: "E-mail zweryfikowany",
    enableAPIKey: "Włącz klucz API",
    failedToUnlock: "Nie udało się odblokować",
    forceUnlock: "Wymuś odblokowanie",
    forgotPassword: "Zapomniałeś hasła",
    forgotPasswordEmailInstructions: "Instrukcje resetowania hasła zostały wysłane na e-mail",
    forgotPasswordUsernameInstructions: "Instrukcje resetowania hasła zostały wysłane na nazwę użytkownika",
    usernameNotValid: "Nieprawidłowa nazwa użytkownika",
    forgotPasswordQuestion: "Zapomniałeś hasła?",
    generate: "Generuj",
    generateNewAPIKey: "Wygeneruj nowy klucz API",
    generatingNewAPIKeyWillInvalidate: "Wygenerowanie nowego klucza API unieważni poprzedni",
    lockUntil: "Zablokowane do",
    logBackIn: "Zaloguj się ponownie",
    loggedIn: "Zalogowano",
    loggedInChangePassword: "Zalogowano – zmień hasło",
    loggedOutInactivity: "Wylogowano z powodu bezczynności",
    loggedOutSuccessfully: "Wylogowano pomyślnie",
    loggingOut: "Wylogowywanie",
    login: "Zaloguj się",
    loginAttempts: "Próby logowania",
    loginUser: "Zaloguj użytkownika",
    loginWithAnotherUser: "Zaloguj się jako inny użytkownik",
    logOut: "Wyloguj się",
    logout: "Wyloguj",
    logoutSuccessful: "Wylogowano pomyślnie",
    logoutUser: "Wyloguj użytkownika",
    newAccountCreated: "Nowe konto utworzone",
    newAPIKeyGenerated: "Nowy klucz API wygenerowany",
    newPassword: "Nowe hasło",
    passed: "Zaliczono",
    passwordResetSuccessfully: "Hasło zresetowane pomyślnie",
    resetPassword: "Zresetuj hasło",
    resetPasswordExpiration: "Wygaśnięcie resetowania hasła",
    resetPasswordToken: "Token resetowania hasła",
    resetYourPassword: "Zresetuj swoje hasło",
    stayLoggedIn: "Pozostań zalogowany",
    successfullyRegisteredFirstUser: "Pomyślnie zarejestrowano pierwszego użytkownika",
    successfullyUnlocked: "Pomyślnie odblokowano",
    tokenRefreshSuccessful: "Token odświeżony pomyślnie",
    unableToVerify: "Nie można zweryfikować",
    username: "Nazwa użytkownika",
    verified: "Zweryfikowano",
    verifiedSuccessfully: "Zweryfikowano pomyślnie",
    verify: "Zweryfikuj",
    verifyUser: "Zweryfikuj użytkownika",
    verifyYourEmail: "Zweryfikuj swój e-mail",
    youAreInactive: "Jesteś nieaktywny",
    youAreReceivingResetPassword: "Otrzymujesz reset hasła",
    youDidNotRequestPassword: "Nie prosiłeś o reset hasła",
  },
  error: {
    accountAlreadyActivated: "Konto już aktywowane",
    autosaving: "Automatyczne zapisywanie",
    correctInvalidFields: "Popraw nieprawidłowe pola",
    deletingFile: "Usuwanie pliku",
    deletingTitle: "Usuwanie tytułu",
    emailOrPasswordIncorrect: "Nieprawidłowy e-mail lub hasło",
    followingFieldsInvalid_one: "Następujące pole jest nieprawidłowe",
    followingFieldsInvalid_other: "Następujące pola są nieprawidłowe",
    incorrectCollection: "Nieprawidłowa kolekcja",
    invalidFileType: "Nieprawidłowy typ pliku",
    invalidFileTypeValue: "Nieprawidłowa wartość typu pliku",
    invalidRequestArgs: "Nieprawidłowe argumenty żądania",
    loadingDocument: "Ładowanie dokumentu",
    localesNotSaved_one: "Lokalizacja nie została zapisana",
    localesNotSaved_other: "Lokalizacje nie zostały zapisane",
    logoutFailed: "Wylogowanie nie powiodło się",
    missingEmail: "Brak e-maila",
    missingIDOfDocument: "Brak ID dokumentu",
    missingIDOfVersion: "Brak ID wersji",
    missingRequiredData: "Brak wymaganych danych",
    noFilesUploaded: "Nie przesłano plików",
    noMatchedField: "Brak pasującego pola",
    notAllowedToAccessPage: "Brak dostępu do strony",
    notAllowedToPerformAction: "Brak uprawnień do wykonania akcji",
    notFound: "Nie znaleziono",
    noUser: "Brak użytkownika",
    previewing: "Podgląd",
    problemUploadingFile: "Problem z przesłaniem pliku",
    tokenInvalidOrExpired: "Token nieprawidłowy lub wygasł",
    tokenNotProvided: "Nie podano tokena",
    unableToDeleteCount: "Nie można usunąć liczby",
    unableToReindexCollection: "Nie można ponownie zindeksować kolekcji",
    unableToUpdateCount: "Nie można zaktualizować liczby",
    unauthorized: "Nieautoryzowany",
    unauthorizedAdmin: "Administrator nieautoryzowany",
    unknown: "Nieznany błąd",
    unPublishingDocument: "Cofanie publikacji dokumentu",
    unspecific: "Niesprecyzowany błąd",
    unverifiedEmail: "Niezweryfikowany e-mail",
    userEmailAlreadyRegistered: "E-mail użytkownika już zarejestrowany",
    userLocked: "Użytkownik zablokowany",
    usernameAlreadyRegistered: "Nazwa użytkownika już zarejestrowana",
    usernameOrPasswordIncorrect: "Nieprawidłowa nazwa użytkownika lub hasło",
    valueMustBeUnique: "Wartość musi być unikalna",
    verificationTokenInvalid: "Nieprawidłowy token weryfikacyjny",
  },
  // ...repeat for fields, folder, general, localization, operators, upload, validation, version (add translations as needed)
};

export default pl;
